### ISSUE TITLE
Simplify won't work when offline

### ISSUE THREAD

**Issue by duncanbeevers** [mmth/simplify_web_suite_core#30]
I see the websocket connection between the Simplify browser extension and the simplify daemon is run through `localhost.tape.im` which resolves to `127.0.0.1`.

Unfortunately, when a system is offline, `localhost.tape.im` won't resolve at all.

Is it necessary to run the websocket through this domain?

**Comment by din** [comment]
Yes, it's necessary because it allows us to use secured web-sockets. Otherwise with the recent Safari release it wouldn't be possible to pass data to the extension at all because Safari doesn't support any other means of passing messages like Google Chrome does. It also simplified our extension for Google Chrome.

**Comment by duncanbeevers** [comment]
@din Tks
